### Register Trainer (web) ###
GET http://localhost:8000/register
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "newpassword",
    "full_name": "Ran Test"
}

### Register Trainer (api) ###
POST http://localhost:8000/api/register
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "newpassword",
    "full_name": "Test Test"
}
